name: utils
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install utils
      run: |
        sudo apt-get -y install apt-utils
        sudo apt-get -y install -y curl 
    - name: make test
      run: make -C 3_Implementation/
